version: '3'
services:
  app:
    build: ./src/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_DATABASE: mydatabase
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=5'
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
  bg:
    build: ./src/background
    tty: true
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_DATABASE: mydatabase
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
